import { NextPageWithLayout } from '@/shared/@types'
import { getData, getDataById } from '@/shared/getFetchData'
import { PostPage } from '@/views/post-view'
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import { QueryClient, dehydrate, useQuery } from 'react-query'

export const getStaticPaths: GetStaticPaths = async () => {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('post', () => getData('https://jsonplaceholder.typicode.com', 'posts'))
  const data = queryClient.getQueryData('post') as any

  const paths = data?.map((post: any) => {
    return {
      params: { id: post.id.toString() },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
  const id = context.params?.id as string
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('post', () => getDataById('https://jsonplaceholder.typicode.com', 'posts', id))

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const Post: NextPageWithLayout = () => {
  const { query } = useRouter()
  const { data: post } = useQuery('post', () => getDataById('https://jsonplaceholder.typicode.com', 'posts', query.id))

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <PostPage post={post} />
    </div>
  )
}

export default Post
