import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { TestingPage } from '@/views/testing-view'

const Testing: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TestingPage />
    </div>
  )
}

export default Testing
