import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { GetServerSideProps, GetStaticProps } from 'next'
import { EpisodesPage } from '@/views/episodes-view'
import { QueryClient, dehydrate, useQuery } from 'react-query'
import { getData } from '@/shared/getFetchData'

export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('episodes', () => getData('https://rickandmortyapi.com/api', 'episode'))

  // if (!data) {
  //   return {
  //     notFound: true,
  //   }
  // }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const Episodes: NextPageWithLayout = () => {
  const { data: episodes } = useQuery('episodes', () => getData('https://rickandmortyapi.com/api', 'episode'))

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <EpisodesPage episodes={episodes.results} />
    </div>
  )
}

export default Episodes
