import { NextPageWithLayout } from '@/shared/@types'
import { getData, getDataById } from '@/shared/getFetchData'
import { CharacterPage } from '@/views/character-view'
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import { QueryClient, dehydrate, useQuery } from 'react-query'

export const getStaticPaths: GetStaticPaths = async () => {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('character', () => getData('https://rickandmortyapi.com/api', 'character'))
  const data = queryClient.getQueryData('character') as any

  const paths = data.results.map((character: any) => {
    return {
      params: { id: character.id.toString() },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
  const id = context.params?.id as string
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('character', () => getDataById('https://rickandmortyapi.com/api', 'character', id))

  // if (!dehydrate(queryClient)) {
  //   return {
  //     notFound: true,
  //   }
  // }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const Character: NextPageWithLayout = () => {
  const { query } = useRouter()
  
  const { data: character } = useQuery('character', () =>
    getDataById('https://rickandmortyapi.com/api', 'character', query.id)
  )

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <CharacterPage character={character} />
    </div>
  )
}

export default Character
