import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { GetStaticProps, GetStaticPropsContext } from 'next'
import { CharactersPage } from '@/views/characters-view'
import { Character } from '@/entities/viewer'
import { FC } from 'react'
import { getData } from '@/shared/getFetchData'
import { QueryClient, dehydrate, useQuery } from 'react-query'

export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('characters', () => getData('https://rickandmortyapi.com/api', 'characters'))

  // if (!queryClient.getQueryData("characters")) {
  //   return {
  //     notFound: true,
  //   }
  // }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const Characters: NextPageWithLayout = () => {
  const { data: characters } = useQuery('characters', () => getData('https://rickandmortyapi.com/api', 'character'))

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <CharactersPage characters={characters.results} />
    </div>
  )
}

export default Characters
