import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { GetServerSideProps } from 'next'
import { LocationsPage } from '@/views/locations-view'
import { QueryClient, dehydrate, useQuery } from 'react-query'
import { getData } from '@/shared/getFetchData'

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient()
  const data = await queryClient.prefetchQuery('locations', () => getData('https://rickandmortyapi.com/api', 'location'))


  // if (!data) {
  //   return {
  //     notFound: true,
  //   }
  // }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const Locations: NextPageWithLayout = () => {
  const { data: locations } = useQuery('locations', () => getData('https://rickandmortyapi.com/api', 'location'))

  return (
    <div>
      <Head>
        <title>Locations</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <LocationsPage locations={locations.results} />
    </div>
  )
}

export default Locations
