import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { ProducsPage } from '@/views/products-view'

const Producs: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <ProducsPage />
    </div>
  )
}

export default Producs
