import { useCurrentAlbum } from '@/entities/album/model/get-current-album-query'
import { NextPageWithLayout } from '@/shared/@types'
import { getData, getDataById } from '@/shared/getFetchData'
import { queryFactory } from '@/shared/lib'
import { AlbumPage } from '@/views/album-view'
import { CharacterPage } from '@/views/character-view'
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import { QueryClient, dehydrate, useQuery } from 'react-query'

export const getStaticPaths: GetStaticPaths = async () => {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('single-album', () => getData('https://jsonplaceholder.typicode.com', 'albums'))
  const data = queryClient.getQueryData('single-album') as any

  const paths = data.map((album: any) => {
    return {
      params: { id: album.id.toString() },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
  const id = context.params?.id as string
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('single-album', () => getDataById('https://jsonplaceholder.typicode.com', 'albums', id))


  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const Album: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <AlbumPage />
    </div>
  )
}

export default Album
